name: 'Wait for commit status'
description: 'Wait until the given commit status matches the expected state before proceeding.'
inputs:
  github-token:
    description: 'Github token for the workflow'
    required: true
  status-context:
    description: 'The string (context) name of the commit status to wait on (e.g., jenkins/build)'
    required: true
  check-interval:
    description: 'Time to wait between checks'
outputs:
  status:
    description: 'The status object'
runs:
  using: 'node12'
  main: 'dist/index.js'